# Generated by Django 3.2.9 on 2021-12-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arrow',
            unique_together={('arrow_of_round', 'score')},
        ),
    ]
