# Generated by Django 4.0.9 on 2023-02-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_unique_together_arrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tiebreak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
