# Generated by Django 4.0.9 on 2023-02-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_tiebreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_actual_zero',
            field=models.BooleanField(default=False, help_text='Set true if the archer really completed the round without scoring a single point. Also useful if the "alteration" returns the score to 0.'),
        ),
    ]
