# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='junior_masters_age',
            field=models.CharField(blank=True, choices=[('', 'None'), ('U21', 'U21'), ('U18', 'U18'), ('U14', 'U14'), ('U12', 'U12')], default='', max_length=3),
        ),
    ]
