# Generated by Django 4.1.2 on 2023-02-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_new_agb_age_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archer',
            name='junior_masters_age',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='wa_age',
        ),
    ]
