# Generated by Django 4.1.2 on 2023-02-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ifaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_ifaa',
            field=models.BooleanField(default=False),
        ),
    ]
