# Generated by Django 4.0.9 on 2023-02-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_round_flint_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_type',
            field=models.CharField(choices=[('F', 'Five Zone Imperial'), ('T', 'AGB Indoor - Ten Zone, no Xs, with hits'), ('X', 'WA Outdoor - Ten Zone, with Xs, no hits'), ('I', 'WA Indoor - Ten Zone, no Xs, no hits'), ('W', 'Worcester'), ('S', 'Score only (e.g. IFAA Indoor)')], max_length=1),
        ),
    ]
