# Generated by Django 4.1.10 on 2023-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_round_scoring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='longest_distance',
            field=models.IntegerField(default=0),
        ),
    ]
