# Generated by Django 4.1.10 on 2023-07-08 12:50

from django.db import migrations


def populate_longest_distance(apps, schema):
    Round = apps.get_model('core', 'Round')
    for r in Round.objects.all():
        r.longest_distance = r.subrounds.order_by('-distance')[0].distance
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_round_longest_distance'),
    ]

    operations = [
        migrations.RunPython(populate_longest_distance, migrations.RunPython.noop),
    ]
