# Generated by Django 5.1.3 on 2025-03-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_populate_longest_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_type',
            field=models.CharField(choices=[('F', 'Five Zone Imperial'), ('T', 'AGB Indoor - Ten Zone, no Xs, with hits'), ('X', 'WA Outdoor - Ten Zone, with Xs, no hits'), ('I', 'WA Indoor - Ten Zone, no Xs, no hits'), ('E', 'Xs are 11 - Eleven Zone, no hits'), ('W', 'Worcester'), ('S', 'Score only (e.g. IFAA Indoor)')], max_length=1),
        ),
    ]
