# Generated by Django 5.1.3 on 2026-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_lancasters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='gender',
            field=models.CharField(choices=[('O', 'Open'), ('G', 'Men'), ('L', 'Women')], max_length=1),
        ),
    ]
