# Generated by Django 5.1.3 on 2026-04-02 19:58

from django.db import migrations, models


def update_2026_scoring_types(apps, editor):
    Round = apps.get_model('core', 'Round')
    Round.objects.filter(scoring_type='X').update(scoring_type='Y')


def back_to_2025_scoring_types(apps, editor):
    Round = apps.get_model('core', 'Round')
    Round.objects.filter(scoring_type='X').update(scoring_type='Y')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_lancasters'),
        ('entries', '0043_scoring_type_session_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_type',
            field=models.CharField(choices=[('F', 'Five Zone Imperial'), ('T', 'AGB Indoor - Ten Zone, no Xs, with hits'), ('X', 'WA Outdoor - (pre-2026)'), ('Y', 'WA Outdoor - Ten Zone, with Xs, no hits'), ('I', 'WA Indoor - Ten Zone, no Xs, no hits'), ('E', 'Xs are 11 - Eleven Zone, no hits'), ('W', 'Worcester'), ('S', 'Score only (e.g. IFAA Indoor)')], max_length=1),
        ),
        migrations.RunPython(
            update_2026_scoring_types,
            back_to_2025_scoring_types,
        ),
    ]
