# Generated by Django 5.1.3 on 2026-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_scoring_type_session_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='codename',
            field=models.CharField(default='UKNOWN', help_text='archeryutils round codename', max_length=50),
        ),
    ]
