# Generated by Django 4.2.3 on 2023-07-18 15:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0035_remove_resultsmode_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entries.competition')),
            ],
        ),
    ]
