# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_auto_20160212_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='use_custom_teams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='custom_team_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
