# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_competition_force_mixed_teams_recurve_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='has_junior_masters_age_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='junior_masters_age',
            field=models.CharField(blank=True, choices=[('', 'None'), ('U21', 'U21'), ('U18', 'U18'), ('U14', 'U14'), ('U12', 'U12')], default='', max_length=3),
        ),
    ]
