# Generated by Django 2.0.2 on 2018-03-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0023_junior_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='barebow_team_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='recurve_team_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
    ]
