# Generated by Django 4.1.2 on 2023-02-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_remove_jm_and_wa_age_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='has_junior_masters_age_groups',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='has_wa_age_groups',
        ),
        migrations.RemoveField(
            model_name='competitionentry',
            name='junior_masters_age',
        ),
        migrations.RemoveField(
            model_name='competitionentry',
            name='wa_age',
        ),
    ]
