# Generated by Django 4.1.2 on 2023-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0030_ifaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='ifaa_division',
            field=models.CharField(blank=True, choices=[('P', 'Professional'), ('C', 'Cub'), ('J', 'Junior'), ('YA', 'Young Adult'), ('A', 'Adult'), ('V', 'Veteran'), ('S', 'Senior')], default='', max_length=2),
        ),
    ]
