# Generated by Django 4.1.7 on 2023-03-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0032_alter_resultsmode_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='split_categories_on_agb_age',
            field=models.BooleanField(default=True),
        ),
    ]
