# Generated by Django 4.1.10 on 2023-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0033_competition_split_categories_on_agb_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='name_override',
            field=models.CharField(blank=True, default='', help_text='Override the recurring tournament name', max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='short_name_override',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
