# Generated by Django 4.1.10 on 2023-07-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0034_competition_name_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsmode',
            name='json',
        ),
    ]
