# Generated by Django 4.2.3 on 2023-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0035_remove_resultsmode_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionentry',
            name='kit_inspected',
            field=models.BooleanField(default=False),
        ),
    ]
