# Generated by Django 5.0 on 2024-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0041_any_bow_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='stay_on_line',
            field=models.BooleanField(default=False),
        ),
    ]
