# Generated by Django 5.1.3 on 2026-04-02 19:58

from django.db import migrations, models


def scoring_type_session_round_populate(apps, editor):
    SessionRound = apps.get_model('entries', 'SessionRound')
    for sr in SessionRound.objects.all():
        sr.scoring_type = sr.shot_round.scoring_type
        sr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0042_stay_on_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionround',
            name='scoring_type',
            field=models.CharField(blank=True, choices=[('F', 'Five Zone Imperial'), ('T', 'AGB Indoor - Ten Zone, no Xs, with hits'), ('X', 'WA Outdoor - (pre-2026)'), ('Y', 'WA Outdoor - Ten Zone, with Xs, no hits'), ('I', 'WA Indoor - Ten Zone, no Xs, no hits'), ('E', 'Xs are 11 - Eleven Zone, no hits'), ('W', 'Worcester'), ('S', 'Score only (e.g. IFAA Indoor)')], max_length=1, null=True),
        ),
        migrations.RunPython(
            scoring_type_session_round_populate,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='sessionround',
            name='scoring_type',
            field=models.CharField(choices=[('F', 'Five Zone Imperial'), ('T', 'AGB Indoor - Ten Zone, no Xs, with hits'), ('X', 'WA Outdoor - (pre-2026)'), ('Y', 'WA Outdoor - Ten Zone, with Xs, no hits'), ('I', 'WA Indoor - Ten Zone, no Xs, no hits'), ('E', 'Xs are 11 - Eleven Zone, no hits'), ('W', 'Worcester'), ('S', 'Score only (e.g. IFAA Indoor)')], max_length=1),
        ),
    ]
