# Generated by Django 5.1.3 on 2026-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0042_stay_on_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='gender',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('G', 'Men'), ('L', 'Women')], max_length=1, null=True),
        ),
    ]
