# Generated by Django 5.1.3 on 2026-01-07 18:38

from django.db import migrations


def populate_entry_gender(apps, schema_editor):
    CompetitionEntry = apps.get_model('entries', 'CompetitionEntry')

    for e in CompetitionEntry.objects.select_related('archer'):
        e.gender = e.archer.gender
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0043_open_gender'),
    ]

    operations = [
        migrations.RunPython(
            populate_entry_gender,
            migrations.RunPython.noop,
        )
    ]
