# Generated by Django 6.0.4 on 2026-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0043_scoring_type_session_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsmode',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
