# Generated by Django 5.1.3 on 2026-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0044_open_gender_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionentry',
            name='gender',
            field=models.CharField(choices=[('O', 'Open'), ('G', 'Men'), ('L', 'Women')], max_length=1),
        ),
    ]
