# Generated by Django 5.1.3 on 2026-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0045_gender_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='use_open_gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='use_open_gender',
            field=models.BooleanField(default=True),
        ),
    ]
