# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_auto_20160212_2223'),
        ('olympic', '0002_auto_20150724_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympicsessionround',
            name='ranking_rounds',
            field=models.ManyToManyField(to='entries.SessionRound'),
        ),
        migrations.AlterField(
            model_name='olympicsessionround',
            name='ranking_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entries.SessionRound'),
        ),
    ]
