# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:38
from __future__ import unicode_literals

from django.db import migrations


def populate_ranking_rounds(apps, editor):
    OlympicSessionRound = apps.get_model('olympic', 'OlympicSessionRound')
    for r in OlympicSessionRound.objects.all():
        r.ranking_rounds.add(r.ranking_round)


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_add_ranking_round_m2m'),
    ]

    operations = [
        migrations.RunPython(populate_ranking_rounds, migrations.RunPython.noop),
    ]
