# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_populate_ranking_round_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympicsessionround',
            name='ranking_round',
        ),
    ]
