# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0006_allow_seeding_and_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='novice',
            field=models.CharField(blank=True, choices=[('N', 'Novice'), ('E', 'Experienced')], max_length=1, null=True),
        ),
    ]
