# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 17:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0007_add_novice_h2h'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wa_ages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'Cadet'), ('J', 'Junior'), ('', 'Senior'), ('M', 'Master')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
