# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0008_add_wa_age_group_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympicround',
            name='team_type',
            field=models.CharField(blank=True, choices=[('', 'Individual'), ('T', 'Team'), ('X', 'Mixed team')], default='', max_length=1),
        ),
    ]
