# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0011_add_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='junior_masters_age',
            field=models.CharField(blank=True, choices=[('', 'None'), ('U21', 'U21'), ('U18', 'U18'), ('U14', 'U14'), ('U12', 'U12')], max_length=3, null=True),
        ),
    ]
