# Generated by Django 4.0.6 on 2022-08-11 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0012_junior_masters_h2h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wa_ages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'U18'), ('J', 'U21'), ('', 'Adult'), ('M', '50+'), ('N', '65+')], max_length=1), blank=True, null=True, size=None),
        ),
    ]
