# Generated by Django 4.0.6 on 2022-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0013_wa_age_group_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('G', 'Men'), ('L', 'Women')], max_length=1, null=True),
        ),
    ]
