# Generated by Django 4.1.2 on 2023-02-03 11:45

from django.db import migrations


def update_categories(apps, schema_editor):
    Category = apps.get_model('olympic', 'Category')

    for c in Category.objects.all():
        if c.wa_ages:
            c.ages = []
            if 'C' in c.wa_ages:
                c.ages.append('U18')
            if 'J' in c.wa_ages:
                c.ages.append('U21')
            if 'M' in c.wa_ages:
                c.ages.append('50+')
            if 'N' in c.wa_ages:
                c.ages.append('65+')
            c.save()
        if c.junior_masters_age:
            c.ages = [c.junior_masters_age]
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0015_update_h2h_cats_age_pt_1'),
    ]

    operations = [
        migrations.RunPython(
            update_categories,
            migrations.RunPython.noop,
        ),
    ]
