# Generated by Django 4.1.2 on 2023-02-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0016_update_h2h_cats_age_pt_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='junior_masters_age',
        ),
        migrations.RemoveField(
            model_name='category',
            name='wa_ages',
        ),
    ]
