# Generated by Django 4.1.2 on 2023-02-03 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0017_update_h2h_cats_age_pt_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('', 'Senior'), ('50+', '50+'), ('65+', '65+'), ('U21', 'U21'), ('U18', 'U18'), ('U16', 'U16'), ('U15', 'U15'), ('U14', 'U14'), ('U12', 'U12'), ('U10', 'U10')], max_length=4), blank=True, null=True, size=None),
        ),
    ]
