# Generated by Django 6.0.4 on 2026-05-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0018_ifaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympicround',
            name='match_type',
            field=models.CharField(choices=[('T', 'Sets (old placing rules)'), ('U', 'Sets'), ('C', 'Score')], max_length=1),
        ),
        migrations.CreateModel(
            name='MatchArrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrow_value', models.PositiveIntegerField()),
                ('arrow_of_round', models.PositiveIntegerField()),
                ('is_x', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic.result')),
            ],
            options={
                'unique_together': {('arrow_of_round', 'result')},
            },
        ),
    ]
