# Generated by Django 6.0.4 on 2026-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0019_new_h2h_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcharrow',
            name='closest',
            field=models.BooleanField(default=False),
        ),
    ]
