# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20170220_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='has_junior_masters_age_groups',
            field=models.BooleanField(default=False),
        ),
    ]
