# Generated by Django 4.1.2 on 2023-02-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_recurve_barebow_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leg',
            name='has_junior_masters_age_groups',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='has_wa_age_groups',
        ),
    ]
