# Generated by Django 4.0.9 on 2023-02-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_ifaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmode',
            name='mode',
            field=models.CharField(choices=[('all-shot', 'By round (include later shoots)'), ('by-round', 'By round'), ('by-round-progressional', 'By round (progressional)'), ('by-session', 'By session'), ('combined-rounds', 'Combined rounds'), ('double-round', 'Double round'), ('seedings', 'Seedings'), ('team', 'Teams'), ('weekend', 'Weekend (Masters style)')], max_length=31),
        ),
    ]
