# Generated by Django 4.2.6 on 2023-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0040_fix_archer_scoring'),
        ('leagues', '0010_leg_split_categories_on_agb_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='non_leg_competitions',
            field=models.ManyToManyField(to='entries.competition'),
        ),
    ]
