# Generated by Django 4.2.6 on 2023-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0040_fix_archer_scoring'),
        ('leagues', '0011_season_non_leg_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='non_leg_competitions',
            field=models.ManyToManyField(blank=True, to='entries.competition'),
        ),
    ]
