# Generated by Django 4.2.6 on 2023-12-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_alter_season_non_leg_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='any_bow_team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
